### ISSUE TITLE
Extract prisms into a dictionary, not an array

### ISSUE THREAD

**Issue by daGoodenough** [daGoodenough/bolt12-prism#18]
Right now in the `get_prism_json` function I extract all the prisms and put them into an array. Instead, I want a dictionary of prism dictionaries each with a key value equal to `prism_id`

**Comment by Harshal662** [comment]
where is the function

**Comment by farscapian** [comment]
@Harshal662 I believe everything is on the dev branch. https://github.com/daGoodenough/bolt12-prism/blob/dab138746d5d34da677066c05d4f0266706f6603/prism-plugin.py#L81

**Comment by Harshal662** [comment]
Or are u merging branches?

**Comment by farscapian** [comment]
I'll let @daGoodenough answer for sure, but I think we're developing full BOLT12 functionality dev (merging into dev). This issue really only applies to the dev branch. I'm new to github. Is there a way to specify a branch that an issue applies to?

**Comment by daGoodenough** [comment]
@Harshal662 Okay sorry about that, should be good to go in the main branch. its the `get_prism_json` function. Currently only used in `deleteprism`.

If you want to just submit a PR for the `get_prism_json` function go for it, otherwise it would be awesome if you add a unique ID to each prism when the `createprism` method is called. This would then be used like so: 
```
prisms: {
 prism1: {
   id: prism1
   },
}
```

Also, there should be an option to pass `offer_id` to the `get_prism_json` method so that, for example, `deleteprism` can just pass the offer id and only get back the one corresponding prism.

**Comment by Harshal662** [comment]
I will try that.

**Comment by daGoodenough** [comment]
I realize now that it might have been unnecessary to do this. What do you think? Is it sufficient to just keep track of the offer_id that corresponds to the prism? I think it should be because each offer should only correspond to one prism.

Submitted a PR removing the id in favor of just using the offer_id. Would appreciate your feedback: https://github.com/daGoodenough/bolt12-prism/pull/22

Either way, I appreciate the other code you contributed. Looks much better already!

**Comment by farscapian** [comment]
I agree, the Offer ID should be sufficient to uniquely identity a prism. This gets back to the definition of a Prism: A Prism is a special BOLT12 Offer that gets split out to multiple recipients."

**Comment by Harshal662** [comment]
Is their anything else I can do?
