### ISSUE TITLE
Error handling: look to see if we can find a route before creating the prism

### ISSUE THREAD

**Issue by daGoodenough** [daGoodenough/bolt12-prism#5]
When we try to create a prism, if no route can be found we might want to return a warning or fail to create the prism

**Comment by farscapian** [comment]
In my view we should stick to the basics. What do you need to create a prism? Names, BOLT12 Offers (or pubkey on legacy keysend), and a split distribution.

We should provide the the ability for the user to see which payouts are persistently failing (and what to do, if anything, with unpaid outlays.

**Comment by daGoodenough** [comment]
improving error handling and keeping track of outlays is sufficient for now. Closing this issue
