### ISSUE TITLE
Add fee that prism node earns

### ISSUE THREAD

**Issue by daGoodenough** [daGoodenough/bolt12-prism#9]
This should be specified on startup of the prism.

you can use `plugin.add_option(foo=bar)` to add `feerate=satoshis`

Or define the fee as a payout in the prism. Set fees as part of the split or have a special fee calculation function.

**Comment by farscapian** [comment]
In my view we should focus on two things: 1) receiver share pays for payout and 2) Prism Owner pays for payouts. This is an accounting problem only.

(2) is implemented/default/implied; all payments from the lightning node ALREADY incur fees to the lightning node. So 1) is the only thing we need to implement at the moment. I definitely prefer we implement this by issuing a Local Stub Offer which gets represented as a receiver share in the Prism. Then, if later we want to CHARGE fees for splitting payments, the "fees" can be added by modifying the receiver share proportion.
